---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-pipelines-cluster
  namespace: kubeflow
spec:
  interval: 1m0s
  path: ./manifests/kustomize/cluster-scoped-resources
  prune: false
  sourceRef:
    kind: GitRepository
    name: kubeflow-pipelines
  targetNamespace: kubeflow

