---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-pipelines
  namespace: kubeflow
spec:
  dependsOn:
  - name: kubeflow-pipelines-cluster
  interval: 1m0s
  path: ./manifests/kustomize/env/platform-agnostic-pns
  prune: false
  sourceRef:
    kind: GitRepository
    name: kubeflow-pipelines
  targetNamespace: kubeflow

